language: android

sudo: required

env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-google_apis-21


before_install:
    - chmod +x gradlew

script:
  - android list targets

  - echo no | android create avd --force -n testemulator -t "android-21" --abi armeabi-v7a
  - echo 'vm.heapSize=512' >> ~/.android/avd/testemulator.ini
  - echo 'hw.ramSize=1024' >> ~/.android/avd/testemulator.ini
  - cat ~/.android/avd/testemulator.ini

  - emulator -avd testemulator -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &